with open('tracker/views.py', 'a', encoding='utf-8') as f:
    f.write('\n@csrf_exempt\n')
    f.write('def cron_inactivity_reminders(request):\n')
    f.write('    if getattr(settings, "CRON_SECRET", None) and request.headers.get("Authorization") != f"Bearer {settings.CRON_SECRET}":\n')
    f.write('        return HttpResponse("Unauthorized", status=401)\n')
    f.write('    \n')
    f.write('    now = timezone.now()\n')
    f.write('    subs = PushSubscription.objects.all()\n')
    f.write('    users_notified = 0\n')
    f.write('    for sub in subs:\n')
    f.write('        user = sub.user\n')
    f.write('        last_mood = YourMoodEntry.objects.filter(user=user).order_by("-date").first()\n')
    f.write('        if not last_mood or last_mood.date < now.date():\n')
    f.write('            send_push_message(\n')
    f.write('                sub, \n')
    f.write('                "Missing You! 🥺", \n')
    f.write('                "Hey, did you forget to add how your day was today? Your partner might be waiting to know!", \n')
    f.write('                "/yourmoodtracker/"\n')
    f.write('            )\n')
    f.write('            users_notified += 1\n')
    f.write('            \n')
    f.write('    return JsonResponse({"status": "success", "notified": users_notified})\n')
print("Appended cron view")
