# Generated by Django 6.0.4 on 2026-05-06 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourMoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_type', models.CharField(choices=[('ecstatic', 'Ecstatic 🤩'), ('happy', 'Happy 😊'), ('calm', 'Calm 😌'), ('sad', 'Low 😔'), ('tired', 'Tired 😴'), ('angry', 'Angry 😡'), ('depressed', 'Depressed ☁️'), ('naughty', 'Naughty 😈'), ('romantic', 'Romantic ❤️'), ('playful', 'Playful 🤪')], default='calm', max_length=20)),
                ('energy_percent', models.IntegerField(default=70)),
                ('sleep_hours', models.FloatField(default=0.0)),
                ('bedtime', models.CharField(default='11:00 PM', max_length=20)),
                ('wake_time', models.CharField(default='06:30 AM', max_length=20)),
                ('journal_text', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to='tracker.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
