# Generated by Django 6.0.4 on 2026-05-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_yourmoodentry_delete_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmoodentry',
            name='naughty_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yourmoodentry',
            name='mood_type',
            field=models.CharField(choices=[('ecstatic', 'Ecstatic 🤩'), ('happy', 'Happy 😊'), ('calm', 'Calm 😌'), ('sad', 'Low 😔'), ('tired', 'Tired 😴'), ('anger', 'Anger 😡'), ('naughty', 'Naughty 😈'), ('romantic', 'Romantic ❤️'), ('playful', 'Playful 🤪')], default='calm', max_length=20),
        ),
    ]
