# Generated by Django 6.0.4 on 2026-05-07 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_yourmoodentry_naughty_percent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietracker',
            old_name='notes',
            new_name='shared_notes',
        ),
        migrations.RenameField(
            model_name='movietracker',
            old_name='rating',
            new_name='tmdb_id',
        ),
        migrations.AddField(
            model_name='movietracker',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movietracker',
            name='imdb_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movietracker',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movietracker',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='movietracker',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movietracker',
            name='movie_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'Series'), ('anime', 'Anime')], default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='movietracker',
            name='status',
            field=models.CharField(choices=[('watchlist', 'Watchlist'), ('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='watchlist', max_length=15),
        ),
        migrations.AlterField(
            model_name='movietracker',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
