# Generated by Django 6.0.4 on 2026-06-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_moviereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='note',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='image',
        ),
        migrations.AddField(
            model_name='memory',
            name='title',
            field=models.CharField(default='New Memory', max_length=300),
        ),
        migrations.CreateModel(
            name='MemoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memories/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tracker.memory')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
    ]
