# Generated by Django 5.0.6 on 2026-06-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_songmemory_cover_url_songmemory_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
