# Generated by Django 5.0.6 on 2026-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_playlist_external_id_playlist_is_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_covers/'),
        ),
    ]
