# Generated by Django 5.0.6 on 2026-06-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_playlist_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dashboard_snaps/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snaps', to='tracker.couple')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
