# Generated by Django 5.0.6 on 2026-06-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PeriodCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cycle_length', models.IntegerField(default=28)),
                ('period_length', models.IntegerField(default=5)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_cycles', to='tracker.couple')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flow', models.CharField(blank=True, max_length=20)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('symptoms', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='tracker.periodcycle')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('cycle', 'date')},
            },
        ),
    ]
