# Generated by Django 5.0.6 on 2026-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_profile_gender_periodcycle_symptomlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmoodentry',
            name='stress_percent',
            field=models.IntegerField(default=20),
        ),
    ]
