# Generated by Django 5.0.6 on 2026-06-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_yourmoodentry_stress_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
